server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /gogo

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gogo?serverTimezone=UTC
    username: root
    password: X123456xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
springfox:
  documentation:
    enabled: on
    #    swagger-ui:
    #      兼容性考虑,为swagger增加一层跳转的url
#      base-url: /swaggerDoc

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: mysql
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'