server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /gogo

spring:
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: DB2
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'